site_name: Python Course 2025
theme:
  favicon: 'img/favicon.ico'
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - admonition


site_url: https://ueapy.github.io/pythoncourse2025-website
repo_url: https://github.com/ueapy/pythoncourse2025-website
site_author: Tiago Silva (after Eliza Karlowska, Denis Sergeev)
docs_dir: src
site_dir: _site

nav:
  - Home: index.md
  - Programme: programme.md
  - Content: content.md
  - Installation: installation.md
